packages:
  - .

allowBuilds:
  esbuild: true
  sharp: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.1
  vite-plus: ^0.2.1
  vitest: ^4.1.8

overrides:
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
    - vite-plus
    - esbuild
  allowedVersions:
    vite: '*'
    vitest: '*'

patchedDependencies:
  react-server-dom-webpack: patches/react-server-dom-webpack.patch
