import { fileURLToPath } from 'node:url'

import babel from '@rolldown/plugin-babel'
import stylex from '@stylexjs/unplugin'
import react, { reactCompilerPreset } from '@vitejs/plugin-react'
import { defineConfig } from 'vite-plus'

export default defineConfig({
	build: {
		rollupOptions: {
			external: ['virtual:stylex:css-only'],
		},
	},
	fmt: {
		arrowParens: 'always',
		ignorePatterns: ['.*'],
		jsxSingleQuote: true,
		printWidth: 80,
		semi: false,
		singleQuote: true,
		sortImports: true,
		sortPackageJson: true,
		trailingComma: 'all',
		useTabs: true,
	},
	lint: {
		categories: {
			correctness: 'off',
		},
		env: {
			builtin: true,
		},
		ignorePatterns: ['.*'],
		jsPlugins: [
			{
				name: 'stylex',
				specifier: '@stylexjs/eslint-plugin',
			},
		],
		options: {
			denyWarnings: true,
			typeAware: true,
		},
		overrides: [
			{
				files: [
					'apps/**/*.{js,jsx,ts,tsx}',
					'packages/react/**/*.{js,jsx,ts,tsx}',
				],
				rules: {
					'react/exhaustive-deps': 'error',
					'react/rules-of-hooks': 'error',
				},
			},
			{
				files: ['**/*.{jsx,tsx}'],
				rules: {
					'react/button-has-type': 'error',
					'react/jsx-key': 'error',
					'react/jsx-no-duplicate-props': 'error',
					'react/jsx-no-target-blank': 'error',
					'react/jsx-no-undef': 'error',
					'react/no-children-prop': 'error',
					'react/no-danger-with-children': 'error',
					'react/no-unknown-property': 'error',
					'react/void-dom-elements-no-children': 'error',
				},
			},
		],
		rules: {
			'constructor-super': 'error',
			'for-direction': 'error',
			'no-array-constructor': 'error',
			'no-async-promise-executor': 'error',
			'no-case-declarations': 'error',
			'no-class-assign': 'error',
			'no-compare-neg-zero': 'error',
			'no-cond-assign': 'error',
			'no-console': 'error',
			'no-const-assign': 'error',
			'no-constant-binary-expression': 'error',
			'no-constant-condition': 'error',
			'no-control-regex': 'error',
			'no-debugger': 'error',
			'no-delete-var': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-else-if': 'error',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-else-return': 'error',
			'no-empty': 'error',
			'no-empty-character-class': 'error',
			'no-empty-pattern': 'error',
			'no-empty-static-block': 'error',
			'no-ex-assign': 'error',
			'no-extra-boolean-cast': 'error',
			'no-fallthrough': 'error',
			'no-func-assign': 'error',
			'no-global-assign': 'error',
			'no-import-assign': 'error',
			'no-invalid-regexp': 'error',
			'no-irregular-whitespace': 'error',
			'no-loss-of-precision': 'error',
			'no-misleading-character-class': 'error',
			'no-new-native-nonconstructor': 'error',
			'no-nonoctal-decimal-escape': 'error',
			'no-obj-calls': 'error',
			'no-prototype-builtins': 'error',
			'no-redeclare': 'off',
			'no-regex-spaces': 'error',
			'no-self-assign': 'error',
			'no-setter-return': 'error',
			'no-shadow-restricted-names': 'error',
			'no-sparse-arrays': 'error',
			'no-this-before-super': 'error',
			'no-unassigned-vars': 'error',
			'no-unexpected-multiline': 'error',
			'no-unsafe-finally': 'error',
			'no-unsafe-negation': 'error',
			'no-unsafe-optional-chaining': 'error',
			'no-unused-expressions': 'error',
			'no-unused-labels': 'error',
			'no-unused-private-class-members': 'error',
			'no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
				},
			],
			'no-useless-backreference': 'error',
			'no-useless-catch': 'error',
			'no-useless-escape': 'error',
			'no-useless-rename': ['error'],
			'no-var': 'error',
			'no-with': 'error',
			'object-shorthand': ['error', 'always'],
			'prefer-const': 'error',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'preserve-caught-error': 'error',
			'require-yield': 'error',
			'sort-keys': 'error',
			'sort-vars': 'error',
			'stylex/enforce-extension': 'error',
			'stylex/no-conflicting-props': 'error',
			'stylex/no-legacy-contextual-styles': 'error',
			'stylex/no-lookahead-selectors': 'error',
			'stylex/no-nonstandard-styles': 'error',
			'stylex/no-unused': 'error',
			'stylex/sort-keys': 'off',
			'stylex/valid-shorthands': 'error',
			'stylex/valid-styles': 'error',
			'typescript/await-thenable': 'error',
			'typescript/ban-ts-comment': 'error',
			'typescript/no-duplicate-enum-values': 'error',
			'typescript/no-empty-object-type': 'off',
			'typescript/no-explicit-any': 'off',
			'typescript/no-extra-non-null-assertion': 'error',
			'typescript/no-floating-promises': 'error',
			'typescript/no-misused-new': 'error',
			'typescript/no-misused-promises': 'error',
			'typescript/no-namespace': 'error',
			'typescript/no-non-null-asserted-optional-chain': 'error',
			'typescript/no-require-imports': 'error',
			'typescript/no-this-alias': 'error',
			'typescript/no-unnecessary-type-constraint': 'error',
			'typescript/no-unsafe-argument': 'off',
			'typescript/no-unsafe-assignment': 'off',
			'typescript/no-unsafe-call': 'off',
			'typescript/no-unsafe-declaration-merging': 'error',
			'typescript/no-unsafe-function-type': 'error',
			'typescript/no-unsafe-member-access': 'off',
			'typescript/no-unsafe-return': 'off',
			'typescript/prefer-as-const': 'error',
			'typescript/prefer-namespace-keyword': 'error',
			'typescript/triple-slash-reference': 'error',
			'use-isnan': 'error',
			'valid-typeof': 'error',
		},
		settings: {
			react: {
				version: '19.2.3',
			},
		},
	},
	plugins: [
		stylex.vite({
			aliases: {
				'@/*': ['src/*'],
			},
			devMode: 'css-only',
			devPersistToDisk: true,
			runtimeInjection: false,
			useCSSLayers: true,
		}),
		react(),
		babel({ presets: [reactCompilerPreset()] }),
	],
	resolve: {
		alias: {
			'@': fileURLToPath(new URL('./src', import.meta.url)),
		},
	},
	run: {
		tasks: {
			ci: {
				command: 'vp check && vpr knip && vpr tsc && vpr test && vpr build',
			},
			commitlint: {
				command: 'commitlint --edit',
			},
			knip: {
				command: 'knip --production --cache',
			},
			pre_commit: {
				command:
					'vp staged && vpr knip && vpr tsc && vpr test --changed && vpr build',
			},
			test: {
				cache: true,
				command: 'vp test',
				input: [
					'vite.config.ts',
					'package.json',
					'pnpm-workspace.yaml',
					'**/src/**/*.{js,ts,jsx,tsx}',
				],
			},
			'test:coverage': {
				cache: true,
				command: 'vp test run --coverage',
				input: [
					'vite.config.ts',
					'package.json',
					'pnpm-workspace.yaml',
					'**/src/**/*.{js,ts,jsx,tsx}',
				],
			},
			tsc: {
				cache: true,
				command: 'tsc --noEmit',
				input: [
					'tsconfig.json',
					'package.json',
					'pnpm-workspace.yaml',
					'**/src/**/*.{js,ts,jsx,tsx}',
				],
			},
		},
	},
	staged: {
		'*': 'vp check --fix',
	},
	test: {
		coverage: {
			exclude: ['**/*.test.*'],
			include: ['**/src/**/*.{js,ts,jsx,tsx}'],
			provider: 'v8',
			reporter: ['text', 'json'],
		},
		environment: 'happy-dom',
		globals: true,
		include: ['**/src/**/*.test.{js,ts,jsx,tsx}'],
	},
})
